import { Router } from "express";
import { analyticsController } from "@/controllers/analytics.controller";
import { authenticate } from "@/middlewares/auth";
import { verifySubscription } from "@/middlewares";
const router = Router();
router.use(authenticate);
router.use(verifySubscription);
router.get("/dashboard", analyticsController.getDashboardStats);
router.get("/sales-summary", analyticsController.getSalesSummary);
router.get("/top-products", analyticsController.getTopProducts);
router.get("/least-selling-products", analyticsController.getLeastSellingProducts);
router.get("/low-stock-products", analyticsController.getLowStockProducts);
router.get("/product-performance/:productId", analyticsController.getProductPerformance);
router.get("/weekly-chart", analyticsController.getWeeklySalesChart);
router.get("/recent-sales", analyticsController.getRecentSales);
export default router;
